---

- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars.yml

  pre_tasks:

    # # Enable this if you run into issues updating
    # - name: Reset dpkg
    #   command: dpkg --configure -a

    - name: Upgrade system
      apt:
        upgrade: dist
        # Need the force_apt_get until
        # https://github.com/ansible/ansible/issues/56832
        force_apt_get: yes
      register: apt_upgrade
      retries: 5
      until: apt_upgrade is success

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        # Need the force_apt_get until
        # https://github.com/ansible/ansible/issues/56832
        force_apt_get: yes
      register: apt_update
      retries: 5
      until: apt_update is success

    # Upgrades screw up DNS, reboot and wait for the RPis to come back
    - name: Reboot the server and wait for it to come back up.
      reboot:

  tasks:
    - include_role:
        name: main
      tags: ['main']

    - name: Remove unneeded apt stuff
      apt:
        autoremove: yes
        # Need the force_apt_get until
        # https://github.com/ansible/ansible/issues/56832
        force_apt_get: yes

    - name: Rebooting hosts
      reboot:
        msg: "Pis are being rebooted"
        reboot_timeout: 5
      ignore_errors: true
