repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, master]

      - id: check-vcs-permalinks

      - id: check-case-conflict

      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=no]

      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key

      - id: pretty-format-json
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint

  - repo: https://github.com/openstack/bashate
    rev: 0.6.0
    hooks:
      - id: bashate
        args: ["--ignore=E003,E006"]

  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.1
    hooks:
      - id: sign-commit

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      - id: script-must-have-extension
        types: [shell, executable]
      # TODO: Shellcheck is mad
      # - id: shellcheck

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        entry: ansible-lint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.20.0
    hooks:
      - id: markdownlint
        language_version: system

# TODO : shell-lint is so mad
# 	- repo: git://github.com/detailyang/pre-commit-shell
# 		rev: v1.0.6
# 		hooks:
# 			- id: shell-lint
# 				args: [--format=json]

# TODO : needs config https://github.com/willthames/ansible-review#configuration
# 	- repo: https://github.com/willthames/ansible-review
# 		rev: 0.14.0rc2
# 		hooks:
# 			- id: ansible-review
