apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-helm-values
  namespace: velero
spec:
  encryptedData:
    values.yaml: AgCbXSAHoJvbveNmDvVRXdyfhUuk3GaH8zTOaDxu6gulUBclOzvNykUV1D4TWhaO76Pr9D8SCwW1cPjT1Zt+KzYQ6aqwf76fxnOExuslGPbNUmJmKYK4RajyqcC67nlOwxsQYLgzOjDmw4qFHaG9D7Go7dFEs8v7wbzA7EPrdxk2kIgCPGljjeVMj1Jmcw3VbrsALDQUKfyNTs2vb2WHityjFbPthCy1Kql7t3XvfCP2g0ZiZXQ1Yy3jcOhsJmN+TQ85ri/9utEL9BNnt/rMuYWcI+oRmZos50wPLOhvewTW6vnmGnyztZBBRerk1Vxv2Kh0BoP4phsuwT3vLUzu4Xditn3PbMJIEatPd9rcFzbhIc0sRbMCoZK5m8socaYi8dcym4MHDSdy3KC5xUMtuFHZQoAFopCK0YqvcrONc1/svdoFwckzLoIYxz0Y4Crh2LVi4uw9/oW/yvK5MT01+HhtR/DQUVV/Kc27Ydcmbq8Bbs134MBPehb9ZvSqFM1HeVqsAbNuG7T2gesH8RKZuphTHLC24wviRzptoHsCT7PuQss4lIO6mALpJw38TYqtftdOjdhXs5LINSKR0p7zbIHh6NaTzkv20/DmU5jYJ6MeaXwYxCzUfNTVhb+78RE1Jysh+85ahfHarGLxUjw4dq6p1mhVp3NdXrqs7JXlNo0KuY1iAGdpNNcSGuvehRIXK70Fg9GtuG+OdUq62R7i95I6zpP2UfvCOUF/MNTz0ifod7geVvwEcTkC5HzRVX43KNNzGcVAMfmk65M+ph0buwDfylAXgmXceq7LVXWghMZALaCQ1mobYKzfczD6enGXyCUHJ6IiPcdDvhUnr6tAOxL2fp2YYK/z0C8zOSkJyvaclU7bnX9SEiz087SVChY1BapY5DcJ2VLuYzKV0TQsj1K2xaHp7x7GBGyv7fmQmZibgRd3pynLHS4nIeAqKJbhBuXl+f4s5HO22SpoRq4OBj2GEpVf9veeOXAaXvtnccC2+DVjF8vQUzydshOUgyUrZPd+NHxZE0k03VNaS/o3Dmeg+2FXoTClnLm26uwv03AbgYjLGFp/RpiBr/xHtBz5NKLa5B3pOKJarX1gQcW8hoYCwtfXyi3TH0lTneQ5mHslSNM6Je7puXTRb0KaCcRR9j98lfyBuyt7qSF2svQkI4qtLAXkBv7k3kuk9F8q7bQVtbox/RkTLO7LZP+bu5wvigKNQ5FWkBugX85c1j/QqH2+gYwNPx9fl1Lxqo4CZnO5sLl1AcQdD56PW0mmClF1gu1Qinf7zjqQ8IM/F9cSdxly9YvL2kXxOL4IR2Rkt7rIYI55UTy8XyRgHZkPvRVt8H5U5Z6ad5FzIrLDx1C4CMQXxeRwVaQk5nT6NchHI5mL0A==
  template:
    metadata:
      creationTimestamp: null
      name: velero-helm-values
      namespace: velero
status: {}

