---

- name: Enable required cgroup features and disable IPv6
  lineinfile:
    path: /boot/firmware/nobtcmd.txt
    backrefs: True
    regexp: '^(.*fixrtc)$'
    line: '\1 ipv6.disable=1 cgroup_memory=1 cgroup_enable=memory'
    state: present

- name: Disable WiFi
  blockinfile:
    path: /boot/firmware/syscfg.txt
    marker: "# {mark} ANSIBLE DISABLE WIFI"
    block: |
      dtoverlay=pi3-disable-wifi
  
- name: Disable Bluetooth
  blockinfile:
    path: /boot/firmware/syscfg.txt
    marker: "# {mark} ANSIBLE DISABLE BLUETOOTH"
    block: |
      dtoverlay=pi3-disable-bt

- name: Disable HDMI
  blockinfile:
    path: /boot/firmware/syscfg.txt
    marker: "# {mark} ANSIBLE DISABLE HDMI"
    block: |
      hdmi_blanking=2

- name: Disable Audio
  blockinfile:
    path: /boot/firmware/syscfg.txt
    marker: "# {mark} ANSIBLE DISABLE AUDIO"
    block: |
      dtparam=audio=off

- name: Disable Uart
  blockinfile:
    path: /boot/firmware/syscfg.txt
    marker: "# {mark} ANSIBLE DISABLE UART"
    block: |
      enable_uart=0

- name: Trottle GPU
  blockinfile:
    path: /boot/firmware/syscfg.txt
    marker: "# {mark} ANSIBLE THROTTLE GPU"
    block: |
      gpu_mem=16

- name: Overclock CPU
  blockinfile:
    path: /boot/firmware/syscfg.txt
    marker: "# {mark} ANSIBLE OVERCLOCK CPU"
    block: |
      over_voltage=2
      arm_freq=1750