---

- name: Install Docker
  shell: 'curl -sSL get.docker.com | sh'
  args:
    warn: false
    creates: /usr/bin/docker

- name: Add user to docker group
  user:
    name: "{{ username }}"
    append: yes
    groups: docker