helmOperator:
  create: false
git:
  url: "git@github.com:onedr0p/homelab-gitops.git"
  branch: master
  path: deployments
image:
  repository: xunholy/flux
  tag: 1.18.0
  pullPolicy: Always
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
prometheus:
  enabled: false
syncGarbageCollection:
  enabled: true
  dry: false
