helmOperator:
  create: false
#
# @CHANGEME - Update url to your public repo URL
#
git:
  url: "git@github.com:onedr0p/homelab-gitops.git"
  branch: master
  path: deployments
image:
  repository: raspbernetes/flux
  tag: 1.18.0
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
prometheus:
  enabled: false
syncGarbageCollection:
  enabled: true
  dry: false
