apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-helm-values
  namespace: velero
spec:
  encryptedData:
    values.yaml: AgCxQ59976Ae+DJ9L9oInlp6z6qwpVpisTROhYy+Hns/GX/BxOKCJquQpV6ttFf/1uwM8dhCssJp2ipUKOlM3Ole7newIhCCRux36R8uDZTysjQjO5D1SiHMTLa0QjLnu/7KfeycxQOjYBn4xNmbGodRRqJgHSwv2AM5EIioc6Qdgsr7PAKkStoquaarVJOBpovjzkm+I+kuemUjJ6fLmsarhJT5PHONq4D+5IqItH7I7/bqqgVXkJARO97DOybYKRmxuPRO0FsmnUQD55FGVtw77QVn7ksAt4P6n1zh3MIDKS9ckbk4fDSZg3wgAYMVJEeSkTThJBm3M5a83FHP7LWnpfdM9w4eH3vrVlF9VJ+rn/NvBibYhwFrnAyI3okh9Pmp6L1FG8ty8ds04dOj32O4pkZv/dxAuP7JO2yaBgrswmXuRAa0ot0phcw2r2FgU8WH65Odym3kHqDVDkETeAEnIqgNVSWxYRE6rccwlU/zVoR1JoQPCYkZhZRaAVhjDQyvlpJmLffqigScBSYT5Q84M+lXVJ/8MPX38+Wc/kAo14eQC2hm9UhVWLgEU96E4ppTj12ErWJeztYZVac9GMg5qs70jKenTc/bXOEmvV2YQo72u4mjKcOMxQnOESZ4Oc3o02UQtkAruNdAM0PsJgT9I6avZ1SPuU+0eh2gj3C01lUv2lUiCMywnP0rPvF/YP3jtG5gmE0PK2nkvhOrPF/tWE8cw+TFcKbQYmhXy+Bqm9vCekNzrGK0LIRfe5HBgRS2FUOA+oPp1Nh8Abbxk861zdJbE1C/d9ABDagMDR4pg6mwILXCZmlvzCaYPckzr6UUFYOjdJtNp81+/r9u6B8wn5u4RutmVT6L/kHUPFw2xv+QBwy8syib8qr1g4TdO2w1ZMmPGcdO1hqjJjGvbdfD4/x+AVTRnDUOjel/HABSBMq3izenINJmEisPN5nBK1Wvq4bP0TdGHkpJ0IupyMOh554u5w8f+Tuo/w620rH6RT8RcAKJqW15CIEXiA3wnrD+0Yt1y4OVMBKa10vmn1T2Uq4fDOEEwIFSXWZSUINPOOeSmwNtKkPjBIKb3xXxLw/gaEofso3D7DPrBcnvdotuNzWY1fDFYdUIlfCfu3YUJ+OSCLKoh5mmle8uFrioumzfeiNjqFwWWCjHAdBKypqCdd4nWPAZdqy+UPoAagmsudp7UfshZnjwzwa08ZHJ+c9hle8Oe2iA69edoOdyYdvLaEkaaB4SOkVkzMuZdbL69fja3ZzQozKIjgeLdPMCTX3DQtxc94eTT1WGUgvTpuJ/htOkZTgdQ+jDywD07zZ2sRIrguOYkmDm+rIBCSs8c6s6g+Q4mnXTEFJ58mP5+TcOYz3bHlpE8Uc=
  template:
    metadata:
      creationTimestamp: null
      name: velero-helm-values
      namespace: velero
status: {}

