apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-helm-values
  namespace: velero
spec:
  encryptedData:
    values.yaml: AgBaqm7BaBsoWpBeJBU9wWipbQc7SrTMfzxMIlxXDV9pxawznWKvvGPyFff1fLj3xL4abdgPwigD8TgaOP/BCIY1R+u+Ssh5ZsEpIDD4r/eF+n3oluOQSry0BI6w6x1sqCHCUpJxLqG9M7eh1EwUZgFB8KGOerkAZVfD8a6mv61LgBcDyrIPkx/gkmzYMkKXo0HKDhenkaow0C0BDHGzr+NUKzoMwdX1ShJablQvHfFubTsabg372j9u1je24VrBdNO2ZEQsF6V6BggX5yECId2ft+lTsPi+pr0f29n5m9fxFNoemsLl7dp13DvKlPnmkGFTT2GtSxx/lj7vCFFmRjnQ9s2XQAtCnH9Ny+8mSNeLnIYkHB3Nl4MLzkOIR9ntmdrepJl/2/orGGe5wpvAQWqqIO/cazQqlt0dX0jrfwrnb/bFzaG+79x5AnGeIOGRRV+TNekYAoQAhn3UZnWr/iywfP+Ea2lOJnosC6RX+I4szT9vejusN1piBBvW0hd+JBydSmAuCQr0k9gtyJS3SkoJkHp9Sf1Y995icvUEhSp2/fGlAoWj1b7LmRHiguihPwrTIutUahDqjfT3AvuaXIZDSRZxfiRm0DnwUvnlyWpWuV6BA/KLfAHKvt95+6hYmvVQutaBZstTu3NIk9Q/0Pi36Jcg598fI3E65e4bEkmVX5iN4Uh/FJP3UUG9wrq7h7SClOKzxYv4OZle+Ad9M0rBGzXfqLJe2/To9JU/RvHciQMskGWjhbp6X+uzrKt+FRcz6w1JWuxfvii6d9ckHLpXlzrH+6DZ31b1Ao7rvhk5msNS/toD8oUFoD5VluNu+es9+6M4bnRHi5ta4OsNVUAgOLRlP9f8s5ljEC1I3foVpMkBzfGSMLPHhVrQL0S/6YCfSDup7dYpXHVR15mmRrSsh3S67wmYIKqe8OaJIadyagvHLDFZz9bKE0/2Vun9kbc0z3hHvAaboCPHDA85669aMoNv8SE3Fiv8Xq2ILRCy59i9+82hiDl8kQ2R8B2YA5gISV2a1gJ7poqlxdueR8dcexnyCx8jhFR4XRzTZPBNmKufnICg1AS46VGqy8EfEUgcUUlfiMBb411O/bvIFogeP/dEPrg63b/suySvi/HXT41PuJz5fFtVyXllM85giC8Kl2RSyrIrqvNxgT2a0DjM1KQ0bS6ajCT7Hl3nuL9tO7HHABMzdSQjBIb8p2BZXwZrnoBsG2M8Ux5CTYR22MU/QBPCQBbLGvSXp086XqtozZcpW8IEr+1SuggJVNXt3TgfAarnPxUmkctC6vTJbKhvQT8KZqhzK3Wttn3qnFiIhQHNLn3nxC3zBinjJ88CPsBeGpwCsbUq2JEfvJ8Yt/cV1J1y9QG5+z0=
  template:
    metadata:
      creationTimestamp: null
      name: velero-helm-values
      namespace: velero
status: {}

