apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-helm-values
  namespace: velero
spec:
  encryptedData:
    values.yaml: AgB8T8vbpxeFr9xal9+rAbrI2qd9i1Jf2VWlQZ1GyizHYcYG2lGuWJqyeigiGEUPZtSF4DYl0jRWmGyl0FG4wCpL8fHiuA4TsemzRhNBPcUPpagfkERFgEdtsXHD6Jv7gozJAWu0jpOkC3V83cp4w2S+4YpA/wsGPRnQHLwiHu1le7VGDvQnDEgBM2QWcY814ueqyDe76ez5/OMaS9U8wd0jpJMU1HcusgX1lKH8/nWHy/Z+gDTY7MEuBKcsGMubl1qyX1WU9EHs+gP3nKVgy0jPtmpmvtsDmiWQgBregDOLxdcmb0BtcGpLP4G27sxoXzYQXNMKYHtPK9jOH2t71m4VAbuuUR70ID3CrTOiOf6hvemEAVetHk61k4VO1puRWztPSq2zfUUEDPNPzWy91uoDtYJ3XDPgbAkpIxIVF5ptbxgc2jaadFyHizcsKbW4kSsys0AtqtQQlxmRi5cchkCfZjwoo0VAgPJjAjtoIU7qNvs8C2zT6xPJcMnnbLh/NxjyhCwP2JEVVEv4zkwrPm3kReK4kuazLt7uDKs/gu+ISHUWdvnvAv/JSrj96Hqnlso8yaJE3d2Y3AVPdwuxtaT8xYaghod8lniPun16X11IUREC+ApmKHSSfv1ahifih2fCZjs9JjidAP+sQsHzzr0g3tZcLrLjJOgF4w+eCvVjMPB3YEqUrGykPZ3sVocv3DqD95W+xNYAmpS2fby4br/8JqN6WiSaH2t+nhAOOp/2mPGWGJ3rbaFSv6ZSF7GZf6J+AmVFSZRDnQXsxiwIpY0qjc0PNfs7ftEGVPQ1LdaG5M9F6H4J0e6bniS0YkqieO/rdvJBkzZLwMKILPuLZlR4VIizUVaxpX9utTKBAbDdMrPu6GqRg2/Pzo5Oxf1OWLr35f8CSxolV1tADIqKYbwMRL2ASV3YBjEIEpSYZ/R21C3kRJSrkov4/ASzOj0Y02AUcnbLiOBqdMsan15mLJYXNSxMov4HOSFAdRJTkmazvsGTwhab7dd7d0fADxyblbd0QU5snsKKi5VqiK/mYt94xRHqVjfqpi3WlSFEjHw6ylaFsC/tXLlGaweKTVmI22P7Y60XM11j/Nc1JetU2rKuBulGZNoJOTVF/qhIhV0eq28UMkDxk/+8tNCEpCcbf0oH6zPN0htTbvu8XdMosfFDZbbo2pzX7Gif1j3i5qzGzTdMFfukAW/0FFrZjp379zu008OxtDUyHefI6htj7Vn4Mz6fCZ0ngzw6ytR22oT69T1KITeGMXtb4W24pBWwqgfDgZ+TgS+eq9B17Vm89G+rhCjX8sVYoE31bBJ7g6jxL+Y9azVF3vWCR9gmIEiGCH6a08e5967wuDwZvvicRJ0XJgH3upX2T/I=
  template:
    metadata:
      creationTimestamp: null
      name: velero-helm-values
      namespace: velero
status: {}

