---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~v0.
spec:
  releaseName: metrics-server
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.8.8
  values:
    image:
      repository: gcr.io/google_containers/metrics-server-arm
      tag: v0.3.6
    tolerations:
    - key: "arm"
      operator: "Exists"