---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(4\.[0-9]+\.[0-9]+(-[0-9]+)?)$'
spec:
  releaseName: pihole
  rollback:
    enable: true
  chart:
    git: https://github.com/MoJo2600/pihole-kubernetes.git
    ref: master
    path: pihole
  values:
    image:
      repository: pihole/pihole
      tag: 4.3.2-1
    replicaCount: 2
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    serviceTCP:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.42.30
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceUDP:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.42.30
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: pihole-svc
    doh: 
      enabled: true
    adlists:
      - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
    persistentVolumeClaim:
      enabled: true
      storageClass: "nfs-client"
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 400Mi
  valueFileSecrets:
  - name: "pihole-helm-values"