apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB8OhhW83xDI967XqIn7dCvyofEv20VT4qnz30/ZSNHBSco5LlTiNqNJurDkS235Beasqtuus1K1HFHQCNiFCFXgRSQQavN5IKwLAR/4Urg1PqO6kubLer79swBo8Wd9JGQFh5pwsu+ft+lD0bOvSUAw9wdjCnmuwqiW2EU0j5pwGf4CeYte+ROINOutQRo2ETSijN9lOTGyglUH33iKpSVV+QNiCI9BrDQnHd8AeSTb86t4ChFEKMyQEiR13QeTiDOdW3hGb6Y03GIap+H7DWh2Jarq4fFewxN6Dr9PzN7dCPUh+75PNP9Yh2RUz6CsTqK+MIi3wKOu5Fk1HIWN6Z+T9RyP+wOo4bDoW0F+PIjArP72CKqilIUauVjncgq/U8tlRvKGQ7DRUHsov25XiSPocNWHWT4rYy4ShC3pz3T1QR92Gq9dIArsRqCRslBumuW+lYCvzfCC1nslKIfQwEr93hCUMIekc8aP/D0xHCVW0dLIt0+qnigSLyjNMaTaUoepDAdqYy5o0PLs05c1mql8wnEMCAlxOhNakz7VQr4mAndHqXiyhgTO7K4FoQ80D4so6FNQQo6LYAVNiuDHb4oCv9V3gCBfDF80DCuUThgjtXKllhzbp5fRy5ZkZYatH71lBTPlU0HAGrpOodTfc6XPcWi53obfjvFjXbizqOis/g0+Txiuybu3oAeIMAhOEjvoph54i6fPzd+uWUVmsRSgKBOBcxJYv8tSblmymyqzIEyKYidocC3rkSuywOG3h1PXFy8sllgj+trsujWssrSfl5BYsxKmLl0J4sN4mdJhKw0gmuv1HXmofhIyuTiqGjOd57XG3m9M69mp0ERBOn+O0Bg3LMnRxtLAQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-helm-values
      namespace: default
status: {}

