apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAwMOx72AktUFQMp57xJO0fQLMIYqjisvnK+2HrRh8L5+gIELsAamjK9LRJKDv9M+UnIYH/QSt0SYuxkbjHNqIH2KuWVJxC6rFMM4nq8+5YyFUW94+Yci+aGuR+AufujwcVDpatrNvQ1OI56w9SEpyZVkUMV0y3K1zVpi91D0bQ1nMRlthktZ9ZkzPJc0PTxt4HjwI6WyLfgz15j6NVY9TQUjXLSBS5acQ3NnNjMhtQYDFCfJNikIAipsPzoA/xMAQvIVtLJjXZKKid86T2eNBxCcZPmVpMlIeeWP7NpGTEtgRTYVRhh6F8eCbPQMZmeQqH39XNp+70Uu0uFQj1+u/wQkZunvzQniQQTh9nu2H91UkdYzb5wh7P+zLogg3BeI1xOdl8C2QxuUydcwPpq3EW8ktd1syTSqYNxk76ClnMPYndvQbvCkPEHqT1uqDJORAz2QY312fCnK0sH3D21JqE/TsKpyPQCbn4YfuCJemjVQsix7+lczSIPmtkspJmOYIzkwQj2ujMnRIUCUYxnG6nay1NghBrds0abQYn2dfNrqXH6zu0LWKnxa7TAKApEXoHxrHd1BB3mmBZNqdM/bEcB8Mk7B4pK/PGEyck3t0PpQhuyUoM/MbULXHZPscSKwPPCq0GFKfGXc89NKs6hIzjaJZnbhLTuL9Krp/3ELWekci9LV7AydaBFQIDTaT4OZRsqDIaNggFEHi3XLQkwtFN5Hs+Vt+Y7LXKF8vCZarQTq1GEevo5gcSx0zTfRhvkaXwNROgn+rM7Egp+3cCmM3LxHTpyFlAY5TXzd39a/P47g+L9Y1drmaa8B6wH353eU784ZO+w/UHuzb7VPOxtOgRF2qL8ZWzmYzqjg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-helm-values
      namespace: default
status: {}

