apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAcfNndv4C3NP0XNwOHKQ2j4eyZiewYUwcEL6I9Y6/LZT4Ykc1OAF2PhQh1lWSyF38RlwDrG1yygSiXP/jRRyu8zs/kucJHAuPgbJLq9MJ/zZX/y3qkc5oHBB7GdsTMMlJrZEBdWyzJizbCCCW0V9T7k8CQuhIjMTdbcJGL/TawfNcOqKbTwSGxoQb6mJyjNQce6k8Rsu1lPe6iz1VqbPGrCjzYBxRFS1RCzrcQ40mDu46HmOkupATVmsITt17vKFW86NgIh5KNzQMiM4ii+3b8ZmIYe/gcEvFCnWVmeSakzT2Y2bR86xln/uPWw7KZ5bHSm8D3FR4istu6S/jNK1K+NPz1vm7qIYF6g+je/XrtSDHIrDRiZQphmgFnn+qTVha1ecg4M9zak5dNyIUPgZLHy5AFTK+wsSnRKcKaqwkJjtl2qy5kF7Bb6qe/B9RpYs4+CsFQ+jDbjm0lCNJTDmTysYNlMB7mbW5q1DTBFDZMtkMmqYIGUvnb5jegdDfeQoJwgH7Ys4OrQbVBs3GZI4xmKUGTVrWasEnXHbBJVxj4Y3oRVjSKAkAgXzgCgb4aSreG3ItIdxw16JHs7rxfCQ2KP1vo+C4z1N1xl67MqoJF5KeC1qwvR3pNxSwH5S4eoUUcOg3qed7JjzpBZsu48UWHIq1XcscHhVFCktOtmgb6hBSJ0M8v/wIRJigjEM3KnwGwTZg5apxVz5zQEtWZHuxoak7KCnDNTSaz8LnCTciviauWfPFshIu3TcBYtnj3C5hOJGrvM6zdGcS387VvkvYLUqwxedg8jZ4Hu/x9PiY8v/Qr2poKFZu30GN3r1EUlC7sdbpUXoCPW8iC5Svi9fSij2qmgah4Wt9S0g==
  template:
    metadata:
      creationTimestamp: null
      name: minio-helm-values
      namespace: default
status: {}

