---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 4.0.1
  values:
    image:
      repository: jessestuart/minio
      tag: RELEASE.2019-10-12T01-39-57Z
    #
    # @CHANGEME - Point to your Persistent Volume Claim
    #
    persistence:
      existingClaim: "nfs-data-pvc"
      subPath: "minio"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
  valueFileSecrets:
  - name: "minio-helm-values"
