apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAMTYwRerdmENIGy4yTBQVfMaML40vpIgD+gt3jisw6TIVWrbxUUoReF+2B3FeSAzS6vsVh2sD+dDBGGnskAGESNIolQHmu0l2TdirRMOwGtqFPv5LuP4K+ej9FLoNFrnTHTGddfucA9pikxaY7xKiHvQuCVrFk027/5vfF2anslp1YCKneLUj3lHEVtI76TKnbzNTq9WJ5bJuqgtxPxEet2Xl2ZddGIgw+iOI9HI6n0FtW2GSjuyiYtv6/fNoU/DctRj5DF2jdjYVmsi25E8V4kjcEhjrdvNTn8sg5dgS+h9cIdhVxh04XAil9PJ9Jt7MQ8R5SF2FUGk3ahXN/6d1c1IHcLaaAN9wss17ZDuC8R7CpNifh93VIEDngidVlbIH9B/uRDqLZtjIX3G4JTmJSQOHLin2SMVI699/P/uA7g/IwpgTZN2xcXQh8pi/hLWKZK+jFsSgltu4ZH5rz1kEQ9j2Ii7Hr3j+rCIfBCXsc53K0UrJ7fPWQs+tnUFim9NRmUKre7gJ/9WbN2HZa4ohSngtlWv5abQO7UQN5KqwxlH8Zi8TRNVhz7l3/DQRAC8cT0Ii0d/qkZXKANGuL8zMMD3zpBhPwwCrLIjDPv/NQeFFzyg8dwmZl6W2ztq5wC1lI8EzDd3Bekx93DjyXOIeVZBVS7MSkWAh/cEbU8QjioUFw2DiTP33hOCb+lw56H1acFS2abWk90+9UHALTjqzR/7CRlmIficDgHLy07hCMn96qsDcsOjNFUocAkDnHeC2kM5iouz6B2e1RC4KZC/utPOElN3vhV9rRz+d4BS8uKQVn0wRdiSsf4/unWauOPPezUOppe88I05y4+q6vkzU5fTRUGGc6UantjA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-helm-values
      namespace: default
status: {}

