---

# See: https://github.com/kubernetes/kubernetes/issues/71305
- name: Use iptables-legacy instead of nftables.
  alternatives:
    name: '{{ item.name }}'
    path: '{{ item.path }}'
  with_items:
    - name: iptables
      path: /usr/sbin/iptables-legacy
    - name: ip6tables
      path: /usr/sbin/ip6tables-legacy
    # - name: ebtables
    #   path: /usr/sbin/ebtables-legacy

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Configure network bridge
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"