---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: qbittorrent
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: qbittorrent
    version: 1.0.1
  values:
    image:
      repository: linuxserver/qbittorrent
      tag: 14.2.0.99201912051435-6796-912b076ubuntu18.04.1-ls56
    uid: 1000
    gid: 100
    guiService:
      type: ClusterIP
    #
    # @CHANGEME - Update to a LB IP in your MetalLB provisioned range and Port that is forwarded to the outside world
    #
    btService:
      type: LoadBalancer
      port: 50413
      loadBalancerIP: 192.168.42.130
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      #
      # A torrent client has to be "pinned" to a node because of port-forwarding rules, persist config on the node as well
      #
      config:
        enabled: true
        storageClass: "local-path"
      data:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        subPath: qbittorrent
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 3000Mi
    #
    # @CHANGEME - Update the hostname to the node you want this deployed to
    #
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - pik3s03
  valueFileSecrets:
  - name: "qbittorrent-helm-values"
