---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbhydra2
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbhydra2
    version: 1.0.2
  values:
    image:
      repository: linuxserver/hydra2
      tag: v2.10.2-ls46
    timezone: "America/New_York"
    puid: 1000
    pgid: 100
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
    probes:
      liveness:
        initialDelaySeconds: 120
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        initialDelaySeconds: 120
        failureThreshold: 5
        timeoutSeconds: 10        
    resources:
      requests:
        memory: 500Mi
        cpu: 25m
      limits:
        memory: 2048Mi
    #
    # @CHANGEME - Update the hostname to the node you want this deployed to
    #
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - pik3s02
  valueFileSecrets:
  - name: "nzbhydra2-helm-values"