---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'glob:v2.*.*-ls*'
spec:
  releaseName: nzbhydra2
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbhydra2
    version: 1.0.0
  values:
    image:
      repository: linuxserver/hydra2
      tag: v2.10.2-ls46
    puid: 1000
    pgid: 100
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: nfs-client
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valueFileSecrets:
  - name: "nzbhydra2-helm-values"