---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~0.
spec:
  releaseName: nginx-ingress
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.25.0
  values:
    controller:
      replicaCount: 3
      image:
        repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm
        tag: 0.26.1
        imagePullPolicy: Always
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.42.24
        externalTrafficPolicy: Local
        enableHttp: true
        enableHttps: false
        targetPorts:
          http: 80
          https: 80
        ports:
          http: 30150         
      resources:
        requests:
          memory: 500Mi
          cpu: 25m
        limits:
          memory: 600Mi
    defaultBackend:
      enabled: false
      image:
        repository: quay.io/kubernetes-ingress-controller/custom-error-pages-arm
        tag: 0.3
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi

          