apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-basic-auth
  namespace: default
spec:
  encryptedData:
    auth: AgCsi+m/l7RGqMHoEzms5rH5EDVVrnboSi8ko/Nwmq1JA92c7Fat7fjpyoM71ZEma4FIxqlDQYmff9o+HgAHleNoER+MOfil7qDucJ1jGaCgrtKZwLgYYsGAmwstcZFMQGN1o9FhOXTc0Ftb5xZl18l2el9o9o0GtJIgfW702mHRcU8UAGMEjypqT1E17k5jDZM2TBkiEJCOTOO9lFxGFEk9eo/ImU6jc+tPEDYP2oQsps2R8ziGHQs9FXn+YSJHax6xZswF0vBBgygT7IGyg55BEVGGqDhHuSpnDznc+Muc/TMEHCzKOXJENbEkbrKyHlGINDjZYNavXVJl27qmAXwHKyuIR1PEeSE2JMYXp7HsDCG9LRWGPRxiMj25sKvwMzlZaaaJ5HzBs1c7joTO/oK8n1mJFYsl9bYrEXmDyVKj27xTA3CVExkgcQRfPzv+ekiG6WwjbwLyaOgJPVGwOU/x5tsU0T7GanC7H/hK7z9t2keAjw7+aZ0BNldRKU7GzW6Rh5cvEbHqyoq705XNRTHw5xFpeAbsRytaVIhl0Q4C3M5Gw3zVVh0iGowEiQ/SGjBfBL0/ua49Ajc0eSv/l6Btzu2GB98VLp5cxGrrQC8xuiVp5SaUha3lp385U3WGCdoVz0cyCP83ypON7YYPH/6bp8o98F8YWn0onkA84v2s3ssA7lTSwTPBLOZdSPkeMyzwiH6uhoon+sCC1TUqNfLaQquJEvIadauY3i/kM4CENewHwWM965PMaTdp
  template:
    metadata:
      creationTimestamp: null
      name: nginx-basic-auth
      namespace: default
status: {}

