apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgBzRFfOl7LenVTHxL8lmGrmxusBgjrBPND/ZOnNdb6pAOyWBd4mdingPb73i4ICyBpVbgDhdY5TMfn7XGkx9jyxfk2FN3nrXaQewOuJ4pXfpC35tBRt6/1PqXzc1+q3DF97fNYbWWIjZLARlTQTJ7fuHYczseuF1QF1QMiqWCFdNo51/yo6cPG1hT2GSfr1z2aAsfjdc+ryPQ7ZJe3oR7stEzuumPgbt4+MTBP7yXY1BnfuHWL3zGyq2fTVLTWhipfLgYZaxUV5xDOJJLqD0ijBoi4ch9VS+sO4VvsDvs939klnZ+7+EGFiYTau2OfFln/L1pMlUdXOVCXVuhYMUJYajddZVyIV70j81YIpFRQBtMOy7rICeGWeMNYRbfZXzGeNNSCjvxy8DPWGW/ELT60C3KI2bF+gKM+g3G4nCKIWe6XHwguGCHB9P4CfNQwuuAZzXhDez+XirNlgUYoPvnK/XFVF3CBZ90qxTJm4NNim5wrbtmafFIkNMpfXfD/eX5gBJCwPbngYF9Jp3OaWQyRq9RpzFp12+Al4iynFTPuJf9xd7rxfN0sfLZhEx/Z+bYIFQlet3856SrmP6LL0a+QHWMJXilg4LmMdqxwR66yrnyzY75I7uZKDnrLs4F883G0PnhRAqJtEaHyHiK3fqk6YN575EoLpKSF3mnPJMIWIBTbY4kyFPcSpT5YUJJuhlsau4RyJPjp8Uk73CWr8d5wiV6ErklcCnRPRJXmQmn1kU11au9lAYQ9bi2uD
  template:
    metadata:
      creationTimestamp: null
      name: nginx-basic-auth
      namespace: kube-system
status: {}

