apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-basic-auth
  namespace: default
spec:
  encryptedData:
    auth: AgBkQDhZcLGre1wfin7mhz7dpIfrNe09XcMVtV7T0Ib41mRxKMJ7cRu7vKFefCNfRl4aEz9tGaaPsxqigUgnH0vcZsSb7S6wOcizkj3is+LE/e2/K3pUKCH76fGEqPvHifoSPMgIx/+aZygjU34TRu0Ho17rFE8wEiAK7W+3Cm7jejERq/fh1yH++WswZhJKNReEaFyJYBUsXthFUE93OdF5ZmHR8XvLXwoevQ8e1lcMfvgSDEjqAScyqXlUPXKXKZGX76DnZuJ2SuMmxCHOI4sLGyfzO+HR56k3c2IAG8obJNeOV6j8OrbHUZpDzElF24JRVfrHPsCyBhW3glpvGfkBlvPZu15ZvywqUrH2Jt3rVK2AjXZ9eB8VeAvLGyRwZclf7qGvC4hnIGn4gBpfJhhP2Yic9n90dHnhbMUT3TZhrLouMcNGdP12hnX8NEiW546tIfUTAk8zxod053l5ZUfPoUMKmxgwA4M4IIezcJur2m7xmGiaTvPekLn1s34OpPxSpbp3JJhrWG5yUOshftyqhhgBQICtJ4Vx9CjebVydUk6KUut+St1qIsa5+3EiynT9sxRGWTdvNaxItyOFJWHPhONM94wwAbxPMaBjkYij0SGFQqj3nWbb9SlKsXjiGL6IixclPXbsE6rHlpzBVBYK6TJhgz19jc9oKsUYBvqIyajX1uIvp8TF8OXRUG6YGT89xXZVoBagrzJW7EYUVG78t4EA
  template:
    metadata:
      creationTimestamp: null
      name: nginx-basic-auth
      namespace: default
status: {}

