---

- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - vars.yml

  #
  # @CHANGEME - Review each role to make sure it's doing what you want to do
  #
  tasks:
    - include_role:
        name: boot
      tags: ['boot']
    - include_role:
        name: packages
      tags: ['packages']
    - include_role:
        name: user
      tags: ['user']
    - include_role:
        name: log2ram
      tags: ['log2ram']
    - include_role:
        name: usbdrive
      tags: ['usbdrive']
    - include_role:
        name: docker
      tags: ['docker']
    - include_role:
        name: userland
      tags: ['userland']

    - name: Rebooting hosts
      reboot:
        msg: "Pis are being rebooted"
        reboot_timeout: 5
      ignore_errors: true
