apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAJbuzSMyEEtRMhQSszD73YRcV/YlSWfB6m2xqj9l2R+ilTZWEm473mt908SOJsCmV2g4nKnpQjVvpsRYPx3UNXAE9ZOCCDusGIOUkOVn/akCFnFLjXlaU0eyoMfOlHSR5EBmmCMxqrcBUy9vNv+PbBsg/SpAqLnf4JIRyZ1dF6jN2oi0fgYJShgwx6LW+2kUvUdn0bmBUZe0l5OxtxYO0GtxaE0snGvnJKr4b4h2hnsp4VcSQJUdo9ZC+kqBIJx1VEzK/ZgMs2StplcrPo01xwHs9xMizh/YPAF9D6wGXfJG27U9vVnvEsABRVktQJqk6+MzM2odKpkAOcXuJMXmJMVbrID9ipndi8p/7Ubc7pSTf1RYenbAsTH6/Eh70MlIt2rwyxY9AvLpg8InAqnWlwuaVfAsJWpkDnuVvcMA+56KS+3+sKnLOM9qIpB+mX9mhuW5I70iQnOBnccW46xB9or1AUJrmJ8yPFW3nTZNmMKEHU5D4q65IpqCwnTQleI1B8aNpHz6OhclNfHsApHWlSz86Li69+xKUf42ubB2Rqcqadt+QTDHLlwjgIGrBN0WkD6A1FasxiXCQSBSNXvzE30oBduJqusbll+KqFpCNmx9RHsTmPxyx7phquLCT6SKkSGCZdEBRbheP4XKa5N471ex7zvgckx+f5jXxYLXdoK72bFkv4pcRyYudPUkvlgUHaQC2HZfJgkv9sbfd/ePE1pMSZClLD+PBEt/SHGGSdRxrJ7Zf4Y4HUHYhxsh74s3l0TZDUs0CvhUUNFary3uTgYSKheHthacanxLWLo6d8TNAD9zUeYUS/7o7Ay53qmyeQOOzZtJnC3zACKIpiNTfFlgf2IPB6Sf4cDcv8bMhZ45XXET1xLvgnXhyUG7oVkaLAskFFtyae7INp8832TurTsEFsX53WMOy672iNuAanYxrDNhQWUs/zXLtd9amH8fgr5CFKcQgkf+UMM6UbgMdqm6eTVJm7WrS5wta3iibEusgvt5/HUXA=
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default
status: {}

