apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBC1E63LPr2yjQLlQ43xKzPeUgBnm57QSMXtDzKujibaz0K7L6LfbVf32WDykOGKWQKEhFgjhBiQDrtTRUT6r7MxCfv+sFLhC+/ciY+k0iTQ6a6yB08ZnuRVhU3iYBgFtfy4wOKNeUWzx/mfi7VMjprTamRcPn/BJRkhoknxI7OoLAeC4ZCOSyavdF/8IuSElyFD02ZiENLojRuF37XogVoqGOKU+Assf7UsG2UlK6yXUt8vmX+bfaTvPj4OWkFEnfNRlWvUx5RaHpYhKrNg8rkmaO+WVgfJ95hBd+gQA4ihaHTAKrAyNcHHwNIKNtSXI7xM5oDVwvASnde9WJPEhE8URV7Uiz/MOyMRCV2MIygavI4DT7vfjOCC7oIPWzbpinVkCPUaStCOgYBsNNXLI751ZyhZlRdSDKkm8ovU7aEYKCJJRpU7F6K0rQ5k+FaGRpZJHdfEmbyJQ3WzzG0/TXk6iOa8NzYm+f496cRmsw29zfKwtohGsalhkfd4mB5gelu9fWzR5YwM6a2WJK1PwDYX9Q606VvLX0+gh5ePql1dod2jpEPVWNRA08q5rDwkGbjqN6Cah2oy4sIjB/eBo5lph1udTier8AhZeDCXLCtmiQCCUdTwqSZcXs7QgS1W5TC1Smx27HncdZvDueM0LFCtKw0NakJ4DP9EvfjNt9ZuQag+jC+5O1AAiUqAVMkaoYzIpZCVbzdiOn8lar4n7Na7wqexc/U8duBrRZClafdQ8elULLiMgS3G7q7U92PZw0tCo2JF5MImus+I6GiB4HcK80GuAM1+YD/4uNFOwlpp/8+KkPo8AqkVVHDQdnFsjQpI78nStrtBUu/1ox0rjxp+kHmmaUm7PS5VqSJmdH6bBgQOracXSgTbw0Z9Eqsxb+Gy5NsM7xiWlI/oUuZsSrr9t3ctlzPcuroQ21FZXw4272fGQxpo6P6TaYWuC+jODNNJm5yckWHQgBPjzPi3pQ3wtNFQQPdlSOcdVxqkq+/4DWh6xFyy6s=
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default
status: {}

