---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: sonarr
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: sonarr
    version: 2.0.7
  values:
    image:
      repository: linuxserver/sonarr
      tag: 3.0.3.661-ls155
      pullPolicy: Always
    timezone: "America/New_York"
    puid: 1000
    pgid: 100
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      #
      # config needs to be local-path, see https://github.com/Sonarr/Sonarr/issues/1886
      #
      config:
        enabled: true
        storageClass: "local-path"
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        accessMode: ReadWriteMany
      tv:
        enabled: true
        existingClaim: nfs-media-pvc
        subPath: Library
        accessMode: ReadWriteMany
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    #
    # @CHANGEME - Update the hostname to the node you want this deployed to
    #
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - pik3s01
  valueFileSecrets:
  - name: "sonarr-helm-values"