apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBxY5VNUaHO6Ay8QZYm+RkmIFNBYIXmzqyGqsi33w/WedpEziogCBQ83fkRbVXWu+o30pqsu/fEN9G2mu16PlRQsluGv7MyoiqaFLSHUUMqfGdQjw6teob18k3MTKxKlNdEyaBC6CTqkdl4zitYakysVeqgCoC7spZp/VZVdeDS/WVDyd3lUjmoLiWV0dVt8LpLAbnlbUxzsG3z7SDBPE6wacxKPOiaY2t1ghVKNNJCA8A1DF0KSY1PRycI08S50NoK6M8G3MiDycjV68xGlpmGept+WU+XYLYH7PrfZuLZSobA8cOeqcM1k8hQcxKOb1kEU59/1t8LC/QIkz2Ugp7JgTxw71tVEedEEl9QxpdsCJNNTLuosPkT/DS2FDobacUmUQzic9EIP2NtO5TNnbjkrf+TR5Sn0I1oULG8eHgWRDXpHnwaRAphKG1nySP7eA2FKs9KveoEqBX03twFIYAjfXo0CzhtW2t8TloBy2AHOICzzk43VBqOqv+3gUHINl7OKm37uxlB3dvRldYpwlm8JZADT8FcLoJjSZU9k1Ewxh05b2WRMmftFKR9SKkSirMO3XyBfeox4m64KIxn2N2fW4XHZ4j4jK7eL8bmGqAI77dbmjj0y28yjHDqAi1ULSHu1k9Wo5Ujodmvm0KZ0/zbIvhAzGgGNC2mY5DfURTutdLNIX2UQkwYYMZfZbK+t/KmgmOEB8VqnjAHOoymbaG1gfLJ++8ZxoPbRZGvcRyMiFub00tJemBgEX/GUF9ABLia3FwMrljjGW+klaEufZRcZW2jExSSW0Mst3OL78/nKOHxHQW0Yci9kje9OYomRI/PAvQmBgdebAAVZpAg2MRoEhN81EHFwr0YvjRGgY1+xMe8i3TNz+qrSzBM3xF7yL2cJh9dpVd6kvCzRqu+fbCAlmyUfu84x7LlkuK4USIiL9v0zWmez9f4RKP3cBD41Wi8MJdivMJmjry23XSYi9gaFvCQQqfTnnpE5HMaK4dWT96ZjIihpwc=
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default
status: {}

