---
- name: Add Docker configuration file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Replace single quotes with double quotes in daemon.json
  replace:
    path: /etc/docker/daemon.json
    regexp: "'"
    replace: "\""

# See: https://github.com/kubernetes/kubernetes/issues/71305
- name: Use iptables-legacy instead of nftables.
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

# # k3s uses Containerd
# - name: Disable Docker
#   systemd:
#     name: docker
#     enabled: no
