---

#
# System
#

- name: Install Common Packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - dnsutils
      - git
      - gnupg2
      - htop
      - iperf3
      - iputils-ping
      - jq
      - less
      - libnss-mdns
      - net-tools
      - nfs-common
      - nmap
      - ntp
      - psmisc
      - python3
      - python3-pip
      - rsync
      - software-properties-common
      - sqlite3
      - tcpdump
      - traceroute
      - tree
      - unattended-upgrades
      - unzip
      - wget
      - zip
    install_recommends: no
    update_cache: yes
    # Need the force_apt_get until
    # https://github.com/ansible/ansible/issues/56832
    force_apt_get: yes
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

#
# Networking
#

# See: https://github.com/kubernetes/kubernetes/issues/71305
- name: Use iptables-legacy instead of nftables.
  alternatives:
    name: '{{ item.name }}'
    path: '{{ item.path }}'
  with_items:
    - name: iptables
      path: /usr/sbin/iptables-legacy
    - name: ip6tables
      path: /usr/sbin/ip6tables-legacy

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Load br_netfilter module at boot
  template:
    src: br_netfilter.conf
    dest: /etc/modules-load.d/br_netfilter.conf

- name: Configure network bridge
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"

#
# Docker
#

- name: Add Docker configuration file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Replace single quotes with double quotes in daemon.json
  replace:
    path: /etc/docker/daemon.json
    regexp: "'"
    replace: "\""

#
# unattended-upgrades
#

- name: Copy unattended-upgrades configuration files in place
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades

#
# log2ram
#

- name: Stop log2ram
  systemd:
    name: log2ram
    state: stopped
  ignore_errors: yes

- name: Cloning log2ram from GitHub
  git:
    repo: https://github.com/azlux/log2ram.git
    dest: /opt/log2ram
    version: "{{log2ram_version}}"

- name: Changing perms of "/opt/log2ram/install.sh"
  file: 
    dest: /opt/log2ram/install.sh
    mode: a+x

- name: Install log2ram
  command: /bin/sh ./install.sh
  args:
    chdir: "/opt/log2ram"

- name: Copy log2ram.conf
  template:
    src: log2ram.conf.j2
    dest: /etc/log2ram.conf