apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgATHhqL4KatSVKuaN1rvEeOBO3eD72E3tbCiUN58ZY0Pb3ZQDh7N8Irfq0BQgamIZQGIQ8nSyeiYDD4ts30AWdRpjGmiOH4+5qvYQHkVR7vElMc/JBdCY4s+EuJ2JwvY8QgBFKkGPnFHO3dtx+3/kSxt9BiUifSqoOKobpMSlGhszN352pD0zK0XxP3duY+h7Z5g+024mYoP3TqZs+LJuRVEVJA2vfa2erc64cOc8HLIXFU36nVcffch+VHUVj/IQaIVP3wmEkmvlU4PVb9nKVzmVf50hG95b1YlAz+/JDws7o8w00AokqV61yWJ3SCz4ZNgfmMCXpzvC2gEiT7jflnSXynStZFosUpM1wNv62urbQz4pWI1525T4s5Q9yWv6aHR2U+w/hExpa30QrE1pufYUO2dOaG6OFggHpCPKwoQnixb8BaMl5xNmJNAravZMZaoKhrEbYchU3xsGLONE4d+1cmlzTLUpMdklzqltcCuo5WW0YftrFPwnQQxnFm8GHoFtncaD+tzFXGGUw3KKqIMtyqZ/MVafOHZ5yFs7lIAZLb/ha8joyZqMU0Cgl5jubWkec84470lSlR9a0zKjWsTUGc8q5yQpLhYO5inlesJywhChM0HLBwQyAlMKaCXzUstR5i4B5dL4hUetu3RWg4QS7DH32zjFhYGrn2oU1IQfXUyQ8DCDVJur+8MuaPJKABuV0mHfXbbhAugANWlyNooTunykSM5pxE6nFO2/dp2wd8CpLLuzHfQ+UhP8ksClxKz/69HXyCRTqMP4onxjWWbr8hWZEb06SVwTkLnO3kS+MQKgEfKvsJy7hXrAiwBkNU46afaCwp9sz3lJxqRxIuauJ0mF1OWoQvgARVvlbV+H3E1L+EwNfTd4fWldci81YanLLVOhZ1ej0QzAMfPGHqkqz58pkuBvmkxYcJBHIcpRkbhfx2DWYh50I0BG5jyK5KGCIx3jSrhmsjdoeyZJ+K/+ggmQPt1+LxF/FEFGSzTcRUZ6egL5c=
  template:
    metadata:
      creationTimestamp: null
      name: nzbget-helm-values
      namespace: default
status: {}

