---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbget
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: nzbget
    version: 2.1.0
  values:
    image:
      repository: linuxserver/nzbget
      tag: v21.0-ls33
    timezone: "America/New_York"
    puid: 1000
    pgid: 100
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    # podAnnotations:
    #   backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        subPath: nzbget
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 400Mi
    #
    # @CHANGEME - Update the hostname to the node you want this deployed to
    #
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - k3s-worker-a
  valueFileSecrets:
  - name: "nzbget-helm-values"