---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'glob:v0.*.*-ls*'
spec:
  releaseName: jackett
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: jackett
    version: 1.0.0
  values:
    image:
      repository: linuxserver/jackett
      tag: v0.12.1136-ls48
    timezone: "America/New_York"
    puid: 1000
    pgid: 100
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    #
    # @CHANGEME - Update the hostname to the node you want this deployed to
    #
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - pik3s02
  valueFileSecrets:
  - name: "jackett-helm-values"