apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAP5KKO/nHTxHGbXII9DlvLSWbT3X94vaJpOyJsAcBgmLmX5rJXUc61b8IfFBelqp0Lj2A5TTrcaCBixOo1JY3lBWpRiSnbwrJHceAmbKjV+1GhmCPUvcKX92TPG79x7UpVpaggc7/sK3i8oKg3lXTfatgR/zZw91zfa1EXTnD+aXZ5rjiq6solIwViqnE8+s3FtSB1ui9U8irC3xuOi+Dq8zS3ABrGOR9dRfuD7yn8BGnjKwclbFVH9zTVSquusYKsG1QsJKn8I5uGT1c+t1aLcWgNbMmNusXgap8WeXpJPt1TdYJoKxKTkKlWkj+89VIKf7vRaHopgjvhhSVHpx/KZBQTdZBXPOVOcrFua9xqgDUnAxS1H3JHQG1Mc8KtwG09uXftUTmoJNJD9xLplVa2OzJ8NK4rmsNj5xTDHnnuD9+R6/tKC1avst9ErtPMygP24/eZMdW4sf+uq72gRtnsy5AARg0D69hJCXBD1/aWcnQW8i88q6zwNWL+i9P885QRq3m9C/MYTI/fL6k7TTxw/CAIUU4fKaqFv+JxsrvDsvUrvYvGxt03fsb7ZqGUenSnRuAWZ5E1Lt+Qq90BukekCstFQOnnI2c8oBXYiISTsqvnUnJh8Z4FZdQqSnP+co6nDVXE6JWMA33Dci8pdfkpOgZbW4A2uxwTd9X8zwIlGp2PQDc276Kby1a7vf6M0DjFYNlWqemWvBW8/2bt5MDHwiZrTOBrw/kflmu7XrVhvyh8eYsquDY66SjhfkUW8nAqYjb3v0wh/6VXM/Iqm/swoAPfYIop7dPwDE+T9IOVLhdyZbeYxNa3KGhcQe0IuMrBDLAJOrTpaAKZA36yEyOk8fgkixqTmZMrYu2uRoGP3rXQCLDZWJcKNqN80EGO3X+I6RileBVB1s4SqaspFVgkJyVWtwJG2321ZVu07H/f/ut5sKTgDakpxmECaENcsrY5cjWTBicDLW5n0oJaj6GOFSczHaDrtE5kH1eDvrbGenYqUbKcXsM=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

