apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAu+Ny5OqP7paBhV2t3QLMC/Su+8W2RC4rKHuVFrHiLgAe+KrDKDhoNJmFm4oEQbQ7XOcVuruB0JvY4nTmfmSTB8gBPYBv4/sKiXUP1LSOtpic0cr13u0wHt/XIHtQMtp4Y3j2mEd9ceOzn7ywF1L+zeQd8E6AQInGrC605AINBQC5wDTMK/EI2RvYPdNWsuRhVHbnFyGt8ufvyYYJdIRkrwkIp+TdnVUDAgFSIfEnij/25kNdVUmjLZTWjg7K7MwF0uqaBoCxvqOpYAVZ1n+hJN+C8/o20hsreV8DJ6pnGzX08AYqUKQnSjrQ4fA5u/aODOBEePLnRu7xzDgJATZtRhLnyAl6JjSfvnFNXoXMC+G214wPjAubWHU+NNYUmbTrhiCE1mHfD17dRyAo1pUJDRYm26YkLb0iiB0dUTjOeCiJtwF2HaOf9AGi24H9AN2fiQK6O1yg613PGNMcfQ+qD52Hj4t+SOxJPRQKdH596ZcicEFjHaFl05uB8dixbgbyWHIMqFs9Un7Tx77oiBuqcwaQhgigSMsXPlkewOUo3JwtnSGz/ilx0UIKeumOg/Z72+WPzg+wvnoxxwtIPkPM1iBMGnHJ7soe0K6k0UNm3QdxvL+E7cNsdc16X5Z3tSqf9jdyube2qob0Lcx205LTrsrZjaASxuhuJ+nU7Y8SbcAkH4C5PObX32p8Xbzv9TLJjFIMRPjhuytmGSz4UUG9l39Rc6D+Hy8I30dR2546Lh+fEh0ET6Jjxnwf63OTP2lpSqyv8Tbmo3FVTfxqC4LjkH/XvggzSkYJH3+PLub6B1ss9EC3TUK5aSHO2DhlDOaa1vGQTh3waImE4z7MUxqsHQW5ZHd1A75ao7cu7YcZnfk/h3Nr6Mmcws/XT6JdnZ2b/Qt5A9Zw0C69c/T3OFyAN+/ILrzy9cHs+uLXPwvBDiF9cMykWYTA1t1FQmer6H4jj+uMlRgmRowEOSK5MGSG8bIY22K3jQP2MMuFKmMFh6DnmzOgAjGA=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

