apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAN2y8ZyvPEr8vL40lxLLA+LcP4zha7YtXc7g3q3VWjShNmAEg5Hls5F5Swr0JcCNcqvp9rMCX3LwroqUj2orqCgnG+sP/kAGDGWEQ8qn9s9+grFCr30hxBBoZU/+YOjIQO9lg5EqXax8uJTUAqH9fwlSmKjF1ISU1Euh6YY6N0XBcdtr059Ip0sqqV/64Ey+kp3PGhlTvPJ+4AEuG4KU7IscMZMOJH+8tyVYzvFaP5MN1rixOkHOrpvAzVZ6yS5KnlnnOPpXpOAE35OwH2/0TejM+5z+kuspcomRTJp5WnPckXgeP4wtRs7TRqbwnVri7HDtW4fozFUZzsWA0YVumVqef2hyj1XMmnpPY7BnHjoPMA7EGglj7Nb9s2m11r9nahjph0eY7W8+/qVPMfbJL5Oy3PAFzBWut/amaZNstlThtEpT8VXoyASUIq4UVExLX3yHye8zKr8SG/cM5fwzDwWYNDeJfzs/gvG8u1fPFcnvyOHJwJnn7PrDcQLAkRlLIwDCSmQS7vUsFz73A+q08kcozLTf8INAHsoACq5EgooULRr7fAlYuiqtGyv6X0+HGx3IgCxwP2HXunMDq/2YjPTfuZZIRJNIR9OQn/0peTOtedQuMriZp8+osMyycVk+ChdyejWAFzNkX4r1iyik2RaAhTP5Nn3qLO0MpIERxeFe5yu3TmeaJs7PxuKU0J0QGAw7HXinXVwQ+1b0M90Z9jdIYHQzYprcLSKgKuhmT1TesVpSSt7VxBYfP9YSY9XqOSt0PNIBv/Z9BHCdWG5ij85yx2QKtKsns/YZzS79S1UF8YcMg2DMeOcDfGlYQAQrNB3p25VdIew5zNq/fton21oZ/Bz2a9D3joUjhZcR9rM7LU2/wUgMTJ6nD4Bec0Jd2CBxDR/hYkkt+D5nufTAjbub+JSLUOb5OgiijyQ0ddHiyK3XRpwnMnRhzEMQkYoX4XyPvWGktGrYTUlXtJbRNcXdOEbdKNE6iS1za8NJaZS3u8Iqqg8w4=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

