apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgA72w7uYwvsM8ih6nZ5M12AYjWs1dkLJMQTL6+JmBk5DPLppgz7HuDy6crIKm/u5/SaENll5Upz/i15+NEXq/dX62yRCBZ8sxDZlU63LDjg5aH6qqBZzQ0Mg7HPcaZWoIPRoM1+gEgRCUb5LCZSkQsydZpLmIz7Bb//YOZySUs8jVzKYJsjhlm6g0R2JJuyYPVOSs0yTYJewHaI9he0c1TvZFMwO5TNt7zVQFfnXA2V8saM1zl6Y12tp5T5D7RRn97kBRigGSPcNE/JE38R7zyFcuERE/6VbgWaQpFiCVLWimsk7Y3ihCXgC08koljgd9Mbgq/VQeGtDLqPCPRUROqu3mX9WjvBQbh/QLT1L/Asmvcn7hlVKvquHqjDaex53KgurCGlQjRHUaLFnUXFvo7VgSFY3wyF2H6FUNJe3gSLSO5I7RvKqjitq154+XX6tZiyioudvxaEDjMKeerFfc8kNR3jeFKAc/EwrceMa3XLwJLSATh5Yw27Ydh4exVtQJEMEuqi5VujLBT9/v6sDXGkBOjnb0+7B44eYH0IivYRIOOvRsijp1qHs9rFfqWdQmOmjIqdIAo7+ACZMQZft4rZcoFh6HdzzjoNftzS9XCR5hBcjXHRDBxLSREBuH3/PSp/VR4GygX38mhN4964Lufdsv2OyZL6faSW+X35S5//8TulQTf7BekJR+/6JZmEqHyL7BaIBh9KkB74pTu6VizKbGxPmV7+g/wuX7LzYYdJxHzWZ7UBd1gk12mJRc4qUbeByvdXqtVIkchwBnhCwbS1sOXYwpz1TclJ4+7yL8b8W9OIXgHQcZ3jOjTGBfbg+Bi7OjM0RMgX/xezAqidzh0rRZrF6VoaQnQfoMHSQmlwqHtu5SwJSUaZdk2FG0J1SNT20ekhIgiDZB1cRnEKcG7uFv8nrPX4SlO3KH9yNxeIZ/j0Q+CO7/LTXi+lRhBc+9GSUR8OPhP9euv2MSNA1sVL3/Rq+XfhHtV7MpGRMb++o7/AYO4ChM8=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

