apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCLJqiwO2Dmy7Kr6/mEPmRh0P3hQAu5a0kkClsRx1AgZz/9zRUbIT5o8w9wRU00u4j4UuqmNapWE1O7DcCZwq3l8pP1PSgzljyJ3pv/1xobA1BL49cprGCFj0TmhDt6mP1gw61gvYSh8UQ/IYw7XjvIcFASoyC/gweGaaty/9wahJNbYiEsXdBGQfRqm4rUdZ4EPeM+OUl5XjeBwmfr1MiJx0Akn6N8+Z8Mq+B0PQTNBK8oenTITKQcZJ4+TQJxfYTz/JCFwKUryLUjXqit+wM9o1NUxw7HiXMfOOuC/1mxhuwcWNFXWFQLaZLVEYyLZ4SHK0rZhnS/XtaKwKhapyB5zmnCyR5o/hGZR0/qqEyqVhi/BzyE/2+hJssMt2g3EAWaVOjojwn6qWR4XhDD2oMIpOIq6P+0SSYrbObv4P1IWiSbuKC2H15nPXHfBbPKuYuTVAiLu1uOzjr3KxGsAl/tUv3mqBF3QXZ/tYyvpx9yr4Vz9DQFzflvUdyrG3WNkBctevH4x0oePDk2RpykX5mprSkdblDu+YEqrw8jhURxiSM0ILHkEhDoyxKDVvqTtp931NUwfrE+iKEDOIGOJjgx9k3SEvceaKm371Trf91/oHeVcfF21zcN0croxHLaedRv3tGQBPZrV5gZZKn6t086gqsWK0yILjMv+ATBHYD9/8KU0CVwYaaiP9xt3TgC7rROvy1CBBBHqPVQbJA8Q8MELKdOP9OejJ4Nnhtq57eJrlJh7jq10+0n9LQgE+tzhvKqiQJ3mDwrzDSdIwRfgQgTG3D3FMxh2441B6LnE2HGP8aDeBJtRPTlS1R2+gBH/OQJ3iDwYm1RnM9z83tXaM6+PaCpXtGzAfOBChsWWR7STIngIjEYOC+OWk6Em+cs2qt7HHadhniwLuIK9HRErE15ohQAghoeLz2ncuyyPAVmSjqyq/rMWHceIBbeqVFW5EWopPDApK83au+kMFoA7D1S33CWwDi9jtuu+KpV5v96KAyGbtMfXj3G8xo4SrtlvPih
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

