apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCZa9mbtSHY7kmwTOlmqZFeUABzaMvks7t/YKUE/YTsPhEPKY/Oaf6n0UUhxfDaCv3ltO0rxXWjB5jWjWaES0lD8nzkBuu3ZriRPbZfppDQVQk+V9DKTkoKs+yWwz5RyTaSQ7fR6aObBOcnRbmivucWCHzl7tdXql2OqQrmRdkSbOVl5hmHneCK5mnfKhT9D+5NusT7nMobOoLzigDuLnV67VgOtuNNuOhfRD3aNqkd0FeDndkcp2mafok2wTD0NfHi9KeVbMbPbJq1VJ6gIA0sKNLfIh1LwcX8krXJfMFp2pI5ukbkDxIdfAK4NRF/aiJArAPRofCLBKyP47pKKX14WF28NXISaVSLxbLRm1pPdFwhv+Q8jnQuQtHZ/3OeduOGUGNuReXsJTYEXHoXkwIJuCp6B0/1AuxP2nPLtlWgAChAmB9frhTDVnNGl8mlMItdDmf3eBbCaczOAwYmaRfggXl7Dvk9A6r+t1KPDPsMiiIoXLCDZo5NpJCG7Vsvd6/G6gNWgM1Td2u+J80uxqbf097DzrRvpR8iei1pUyq/20emC9vXRzX61RLKJiO0vXED5RlbqU1EkOfKVPIzkMNoh1WYPS34+Dm8kzRUK83t2Jf7wJBkhyexLHTL9+iS4uk39fEhY1aBEFRE1J5fM2BoKW/Vx4RGHP8I3SmZ/uyuhaOYV8b0gaSdxvf386TXiEoNQfB75Tgrx2cQG2M8PYhObQv0v0efYz0zhJH/JX9SI3YW5MkWPWOUjE+GZCgFp3F7aALwCEJV0L3Ifv2MEGRoB8PSUlSpD1IgV0d6EqzHcp1/t5y33CZaFJbYmNtwlYlOWmjQOvYqb71byZNQZ4A3+5Cuma/VKLXpwj4mh4ooqp6UdhaZnZI1CCyA/WqdK8Iou3+e6SmOoG+vEr0exbU6fhUMQ7eb9jf/T8Y5coGuCsJBEodB8A48PWilCLRswXPFnhmhr3xb8H3DZSWy4nhtCeZ+mWUljxj7RhXoyuIwEaQQMXuN+0I=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

