apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCBU2/726+n7hV5rfm7ufQEBFoj6vZu9WOwLK4pZGn7SczKUWuaEiLIxpe9wBrLWY0Dpy9LGprhvSKBdEPimlzmU+s6JjDR009HnHDUk+qJeGyiB23SfqSA+bbfhhWaq4dMGyibN/O/xe3iztTUYU4isnz3SfScWG0ijHpyTegSJUOKvWvx22xUfaUhX1U0yLDhR31Ah25QqfEG//UBjPaWl54qIiKZ+ovb6qEQ96WQmlPjtH6PW0/zXKIbIVqfvSaxdVFWRWz9FiB3/tItP2R/wU6n8rUspEEhi9RIfoAKg0JzFyE1UqFkg+42P8E7Ne0+xMxZCtlF+p4ilhrRc934TMYQ/JlUWs7vWZB39Z0YcnN375Ihrc4IGOH+9GXLJgDDq3r/L4PyrqN+zxYegjb/VtKW54JGI6hmNQiTEvWyGKgVi10SnDnjSWTlPO2fpwJ19/nNzPZmKJQoUu/UU+HFjbQlgX1up3KQaJjVEOskRxcW16LCRBNtbkG2g0brSx00dXNsgDSsmooYAWKnUpyNA9LoYQrdRrsIKwHSzFn446c7bK3POQQAdkVA9fA8a/WNjat0Q9fsXkicAyN2ZpSvhqWA8uEYZrdhRCuSDmSDaUEdERNcRk97c79fRW68LbUQe3Hx04JfmXDaMdG3/KvtYEXQg6HF5lEPDrvBWoqpnPEfAd45pIZgqi4ceitsNHGeenPlaY6pC9fKPEGxuJ4jX2KzwnrSOX7+ofxywxOQCV1y8szUW4Ts9hmgj5+/fyDQSb7utfywezVwFcrmCqIdajvU4OaEiQRyZaWijFqs0GGE/gCHHQrz/1DvFKh3my+Fzi/MsTuGYjUW5DvS0vmUWuJhJsWFDTQfP81f0oLF/uG+I9WLa468vSDVvFDBPNw0wOOw9At68/Qtfi3KqL7tT/gzK+i6mSI6teSDCwSt00pG8kOJrFbHpKrClGbG7pdyYa6kQJuhPC+EYxbccBBAirw67u9gNOnnF9e652JROFoSmL7D0oI=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

