createCRD: true
git:
  ssh:
    secretName: flux-git-deploy
image:
  repository: onedr0p/helm-operator-arm
  tag: v1.0.0-rc4
  pullPolicy: Always
chartsSyncInterval: "5m"
statusUpdateInterval: "5m"
prometheus:
  enabled: false