createCRD: true
git:
  ssh:
    secretName: flux-git-deploy
image:
  repository: raspbernetes/helm-operator
  tag: v1.0.0-rc9
chartsSyncInterval: "5m"
statusUpdateInterval: "5m"
helm:
  versions: "v3"
prometheus:
  enabled: false
