createCRD: true
git:
  ssh:
    secretName: flux-git-deploy
image:
  repository: onedr0p/helm-operator
  tag: v1.0.0-rc7
  pullPolicy: Always
chartsSyncInterval: "5m"
statusUpdateInterval: "5m"
helm:
  versions: "v3"
prometheus:
  enabled: false
