apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dyndns-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBxzhjORLFgdRHVnTe1daqqgiBgFjAA8L12DZAOV0hTJurbLg2ASLeqDsAAkMu9l2PNyq8CR0rV8EC8tlrubbzf0pR6d71aOpgJs4UZJQnPIJYT7LsGB0mBdsoxGXIcP0BG+xKnZOQ202DUXhb6GMtTqXhewt82jKMdUr0Ixoloj/hKV3adOnB6ZpOu/akTtoeLQtBWV7//IYDCysXjUq4oUxhvLg3O2rqtdfkro3XUBGqCOIVo7Vm6ktYO88ycpU3/QuEDkopQosR7Fmn9/sSH6id+mFK2YDGeeqUeQ8knYXBBJpEX+loFb/m5+6oNLWbqAO+rM4Px//kkmLrz/zpsCJD2J5rqdjvYDZK6asQDaM7dwI5jz812T2HwW6c1HXPibXQ9V4PymSyUYlFBBsS13awOVdvLWgyHHZdLPUvdi9C9tQS0jDUZbEu5gp9MklWPkLJvVw5LaLNOVlScFtvVC07hW+tyH5DmL9a/Hebuuupxl0ywm1cAxwtjO6u61uPv8CUoShV4+KmXNwUracXN5ZYQJ2LTVqPfpMzbq/9YqquYkgAnL6781R/B+4wMCtumLW8b7Eiv1mLpoxWJF/eRbm2whAQZGQszLopbkgTWrVy0nl4ewkbbUdaNApmhFCj4Xsi72AcI2wFEjsVm15XNdgJzt0MOA3vaNaptmb01Azxl2Orly8xE/2Ii0s9Q9LLcgs1dPauDj2R1FshZF+vTYeOVFfzcak+qhkhkevB1elIHTMnU0jDoqZVQ7swMeGW3byo2DjuYUwcbg/v4oWQGPzeDoLQEIcKY6rfWq2szLUh1tmvhHd7pdc3Rc3+nnqaGe6UsPU5Dgk/kKONfuQQ1DuABXDrCEB2bimRcJD0rqjCQdknDcQIKVt6dHW2BAuEIiGfwAw1u+Og=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dyndns-helm-values
      namespace: default
status: {}

