---
- name: Add Docker configuration file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Replace single quotes with double quotes in daemon.json
  replace:
    path: /etc/docker/daemon.json
    regexp: "'"
    replace: "\""

# # k3s uses Containerd
# - name: Disable Docker
#   systemd:
#     name: docker
#     enabled: no
