apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
spec:
  storageClassName: data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #
  # @CHANGEME - Update server and path to your NFS server
  #
  nfs:
    server: 192.168.1.170
    path: "/share/Kubernetes-Data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 1Mi